# 11/08/2021 - Run highland samples
READS_DIR: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/mapping_results/processed_reads
PREFIX: African_chicken_SV
# SAMPLE_LIST: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population-structural-var-calling-smoove/african_samples_population_list.csv
SAMPLE_LIST: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population-structural-var-calling-smoove/sample_list.csv
OUTDIR: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population_SV_calling_results/All_samples
REFERENCE: /lustre/nobackup/WUR/ABGC/shared/public_data_store/genomes/chicken/Gallus_gallus.GRCg6a.dna.toplevel.fa
CONTIGS_IGNORE: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population-structural-var-calling-smoove/contigs_to_ignore.txt
SPECIES: gallus_gallus

