READS_DIR: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/mapping_results/processed_reads
PREFIX: Highland
# SAMPLE_LIST: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population-structural-var-calling-lumpy/sample_lists/Highland_sample_list.txt
SAMPLE_LIST: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population-structural-var-calling-lumpy/test_reads.txt
# SAMPLE_LIST: test_reads.txt
OUTDIR: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population_SV_calling_results/Highland_smoove/
REFERENCE: /lustre/nobackup/WUR/ABGC/shared/public_data_store/genomes/chicken/Gallus_gallus.GRCg6a.dna.toplevel.fa
CONTIGS_IGNORE: /lustre/nobackup/WUR/ABGC/shared/Chicken/Africa/population-structural-var-calling-smoove/contigs_to_ignore.txt